// defaults.ts — static configuration for the Labyrinth game: the tweak defaults,
// the fixed daily maze seed/size, and the key→direction table.

import type { Tweaks } from '../types'

export const TWEAK_DEFAULTS: Tweaks = {
  "world": "Maze Runner",
  "mrTime": "Day",
  "weather": "Clear",
  "rainAmt": 0.32,
  "stormClouds": 0.9,
  "lightning": true,
  "vines": true,
  "vineStyle": "Leaves",
  "vineDensity": 0.5,
  "vineLength": 0.55,
  "vineCloseness": 16,
  "vineRandomness": 0.55,
  "wind": true,
  "windAmt": 0.5,
  "pebbles": true,
  "pebbleDensity": 0.26,
  "pebbleSize": 1,
  "pebbleRandom": 1,
  "sky": true,
  "skyBlue": 0.5,
  "sunAz": 30,
  "sunHeight": 0.32,
  "starDensity": 0.24,
  "landmark": true,
  "spireCount": 18,
  "spireHeight": 1,
  "clouds": true,
  "cloudAmount": 0.28,
  "cloudSpeed": 1,
  "cloudShade": 0,
  "cloudColor": "#bcc3c7",
  "cloudDepth": 0.6,
  "groundLife": true,
  "groundLifeAmt": 0.28,
  "driftLeaves": true,
  "driftAmt": 0.24,
  "driftDir": 45,
  "driftSpeed": 1,
  "bugs": true,
  "bugAmt": 0.3,
  "floorDetail": true,
  "grateAmt": 0.16,
  "stainAmount": 1,
  "crackAmount": 1,
  "runes": true,
  "runeGlow": 0.5,
  "markerColor": "#ff7a59",
  "torchRadius": 2,
  "falloff": 1.4,
  "tweenSpeed": 0.2,
  "showMinimap": true,
  "ao": true,
  "aoStrength": 0.65,
  "flicker": true,
  "flickerAmt": 0.5,
  "haze": true,
  "hazeAmt": 0.22,
  "grain": true,
  "grainAmt": 0.35,
  "headBob": true,
  "bobAmt": 0.6,
  "sway": true,
  "swayAmt": 0.5,
  "audioMuted": false,
  "audioVolume": 0.8,
  "soundFootsteps": true,
  "footstepVolume": 0.5,
  "soundLeaves": true,
  "leavesVolume": 0.5,
  "leavesAmt": 0.6,
  "soundBreathing": true,
  "breathVolume": 1,
  "breathAmt": 0.5,
  "soundRain": true,
  "rainVolume": 0.35,
  "soundWind": true,
  "windVolume": 0.3,
  "soundFactory": false,
  "factoryVolume": 0.25,
  "factoryDistance": 0.6,
  "soundGrowl": true,
  "growlVolume": 0.9,
  "growlIdleSec": 5,
  "growlDuck": 0.6,
  "soundThunder": true,
  "thunderVolume": 0.7,
  "thunderGap": 9,
  "exitVolume": 0.9,
  "soundMusic": true,
  "musicVolume": 0.18
}

export const DAILY_SEED = 20260602; // identical maze for everyone today
export const MAZE_CELLS = 23;
export const KEY_DIR: Record<string, [number, number]> = {
  ArrowUp: [0, -1], ArrowDown: [0, 1], ArrowLeft: [-1, 0], ArrowRight: [1, 0],
  w: [0, -1], s: [0, 1], a: [-1, 0], d: [1, 0], W: [0, -1], S: [0, 1], A: [-1, 0], D: [1, 0],
};
